apiVersion: v1
kind: Service
metadata:
  name: sketchbrain-trainer-svc
  labels:
    app: sketchbrain-trainer
spec:
  type: NodePort
  ports:
    - name: backend-port
      port: 9000
      targetPort: 9000
      nodePort: 32767
  selector:
    app: sketchbrain-trainer