#ONLY FOR EXAMPLES.
apiVersion: v1
kind: Service
metadata:
  name: training-container-svc
  labels:
    app: training-worker
spec:
  selector:
    app: training-worker
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 1234