name: Test & Build & Deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: sketchbrain-trainer
      DOCKER_TAG: 1.0.${{ github.run_number }}
      CONFIG_FILE: src/main/resources/application.yaml
      BOOTSTRAP_FILE: src/main/resources/bootstrap.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace application.yaml
        run: echo "${{ secrets.PROPERTIES }}" > ${{ env.CONFIG_FILE  }}

      - name: Replace bootstrap.yaml
        run: echo "${{ secrets.BOOTSTRAP }}" > ${{ env.BOOTSTRAP_FILE }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle builds with prod
        run: ./gradlew bootBuildImage -Pprofile=prod --imageName=${{ secrets.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image to DockerHub
        run : docker push ${{ secrets.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: sketchbrain-trainer
      DOCKER_TAG: 1.0.${{ github.run_number }}
      DEPLOY_YAML: src/main/resources/yamls/TrainerDeployment.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set K8S Config
        run: mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Change Image Name In Yaml
        run: sed -i 's/#VERSION_STRING#/${{ secrets.DOCKER_USER }}\/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}/g' ${{ env.DEPLOY_YAML }}

      - name: Replace Configmap string in Yaml
        run: sed -i 's/#CONFIG_MAPS#/${{ secrets.CONFIGMAP_NAME }}/g' ${{ env.DEPLOY_YAML }}

      - name: Deploy on K8S
        run: kubectl apply -f ${{ env.DEPLOY_YAML }}